version: "3"

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: crm_spa
    container_name: crm_spa
    restart: unless-stopped
    ports:
      - "3001:8080"
    networks:
      - app-network
    command: npm start

networks:
  app-network:
    driver: bridge

volumes:
  node_modules:
